[36m[2019-01-28 09:12:36,688] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 09:12:53,959] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 09:12:53,960] [log.py:91] [log:__console] [INFO]- 获取到总价格：37380[0m
[32m[2019-01-28 09:12:53,961] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 09:12:53,999] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 09:12:54,004] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 09:12:54,004] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 09:12:54,008] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 09:12:54,008] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1479584, 'taskType': 1, 'taskSource': 1, 'taskId': 62071, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a1bf338418674f5fa27f92395eea26da', 'orderNo': '390213472', 'depCity': 'HND', 'arrCity': 'PVG', 'fromDate': '2019-04-10', 'retDate': None, 'flightNumber': 'MM899', 'tripType': 1, 'name': 'LIN/XIUQIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '4ND3QD', 'price': 37380, 'baggagePrice': 6800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'HND', 'arr': 'PVG', 'depDate': '201904100245', 'arrDate': '201904100500', 'carrier': 'MM', 'flightNumber': 'MM899'}], 'retSegments': None, 'passengers': [{'name': 'LIN/XIUQIN', 'gender': 'F', 'birthday': '19760918', 'nationality': 'CN'}, {'name': 'GU/GUOXIANG', 'gender': 'M', 'birthday': '19760802', 'nationality': 'CN'}], 'baggages': [{'name': 'LIN/XIUQIN', 'baggageWeight': 20, 'dep': 'HND', 'arr': 'PVG'}], 'updateTime': 1548396129000, 'createTime': 1548396129000}[0m
[36m[2019-01-28 09:16:26,393] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 09:16:39,265] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 09:16:39,267] [log.py:91] [log:__console] [INFO]- 获取到总价格：37380[0m
[32m[2019-01-28 09:16:39,268] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 09:16:39,299] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[36m[2019-01-28 09:28:46,375] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 09:29:02,554] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 09:29:02,556] [log.py:91] [log:__console] [INFO]- 获取到总价格：37380[0m
[32m[2019-01-28 09:29:02,557] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 09:29:02,589] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 09:29:15,360] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 09:29:15,361] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 09:29:15,367] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 09:29:15,368] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1479584, 'taskType': 1, 'taskSource': 1, 'taskId': 62071, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a1bf338418674f5fa27f92395eea26da', 'orderNo': '390213472', 'depCity': 'HND', 'arrCity': 'PVG', 'fromDate': '2019-04-10', 'retDate': None, 'flightNumber': 'MM899', 'tripType': 1, 'name': 'LIN/XIUQIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '4ND3QD', 'price': 37380, 'baggagePrice': 6800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'HND', 'arr': 'PVG', 'depDate': '201904100245', 'arrDate': '201904100500', 'carrier': 'MM', 'flightNumber': 'MM899'}], 'retSegments': None, 'passengers': [{'name': 'LIN/XIUQIN', 'gender': 'F', 'birthday': '19630416', 'nationality': 'CN'}, {'name': 'GU/GUOXIANG', 'gender': 'M', 'birthday': '19630602', 'nationality': 'CN'}], 'baggages': [{'name': 'LIN/XIUQIN', 'baggageWeight': 20, 'dep': 'HND', 'arr': 'PVG'}], 'updateTime': 1548396129000, 'createTime': 1548396129000}[0m
[36m[2019-01-28 09:34:25,487] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 09:34:40,763] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 09:34:40,764] [log.py:91] [log:__console] [INFO]- 获取到总价格：37380[0m
[32m[2019-01-28 09:34:40,765] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 09:34:40,796] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 09:34:40,802] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 09:34:40,802] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 09:34:40,806] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 09:34:40,807] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1479584, 'taskType': 1, 'taskSource': 1, 'taskId': 62071, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a1bf338418674f5fa27f92395eea26da', 'orderNo': '390213472', 'depCity': 'HND', 'arrCity': 'PVG', 'fromDate': '2019-04-10', 'retDate': None, 'flightNumber': 'MM899', 'tripType': 1, 'name': 'LIN/XIUQIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '4ND3QD', 'price': 30580, 'baggagePrice': 6800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'HND', 'arr': 'PVG', 'depDate': '201904100245', 'arrDate': '201904100500', 'carrier': 'MM', 'flightNumber': 'MM899'}], 'retSegments': None, 'passengers': [{'name': 'LIN/XIUQIN', 'gender': 'F', 'birthday': '19630416', 'nationality': 'CN'}, {'name': 'GU/GUOXIANG', 'gender': 'M', 'birthday': '19630602', 'nationality': 'CN'}], 'baggages': [{'name': 'LIN/XIUQIN', 'baggageWeight': 20, 'dep': 'HND', 'arr': 'PVG'}], 'updateTime': 1548396129000, 'createTime': 1548396129000}[0m
[36m[2019-01-28 09:37:56,358] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 09:38:07,615] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 09:38:07,616] [log.py:91] [log:__console] [INFO]- 获取到总价格：23280[0m
[32m[2019-01-28 09:38:07,616] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 09:38:07,651] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 09:38:07,657] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 09:38:07,658] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 09:38:07,661] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 09:38:07,661] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'AN/JUNHYEON', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'Y98457', 'price': 23280, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'PUS', 'depDate': '201902211350', 'arrDate': '201902211525', 'carrier': 'MM', 'flightNumber': 'MM017'}], 'retSegments': None, 'passengers': [{'name': 'AN/JUNHYEON', 'gender': 'M', 'birthday': '19691115', 'nationality': 'KR'}, {'name': 'AN/YEONJIN', 'gender': 'F', 'birthday': '19991227', 'nationality': 'KR'}, {'name': 'AN/WOOJIN', 'gender': 'M', 'birthday': '20020424', 'nationality': 'KR'}], 'baggages': [], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 10:57:00,145] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[36m[2019-01-28 10:59:10,472] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 10:59:12,926] [log.py:91] [log:__console] [INFO]- 找不到订单[0m
[31m[2019-01-28 10:59:12,927] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'NoneType' object has no attribute 'group'[0m
[32m[2019-01-28 10:59:12,928] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[31m[2019-01-28 10:59:12,931] [log.py:97] [log:__console] [ERROR]- 获取航班详细信息失败，错误信息是：list index out of range[0m
[32m[2019-01-28 10:59:12,932] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 10:59:12,934] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 10:59:12,934] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'N', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '获取信息失败', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'AN/JUNHYEON', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'BRTQQ3', 'price': 0.0, 'baggagePrice': 0, 'cur': 'CNY', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': [], 'baggages': [], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 11:02:27,456] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 11:02:39,649] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 11:02:39,650] [log.py:91] [log:__console] [INFO]- 获取到总价格：15760[0m
[32m[2019-01-28 11:02:39,651] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 11:02:39,676] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 11:02:39,680] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 11:02:39,680] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 11:02:39,683] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 11:02:39,683] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'CHEN/ZHIXUAN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'BRTQQ3', 'price': 15760, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'PVG', 'depDate': '201903312210', 'arrDate': '201904010005', 'carrier': 'MM', 'flightNumber': 'MM079'}], 'retSegments': None, 'passengers': [{'name': 'CHEN/ZHIXUAN', 'gender': 'M', 'birthday': '19990208', 'nationality': 'CN'}], 'baggages': [], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 11:07:33,213] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 11:07:46,460] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 11:07:46,464] [log.py:91] [log:__console] [INFO]- 获取到总价格：15760[0m
[32m[2019-01-28 11:07:46,465] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 11:08:02,581] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 11:08:02,602] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 11:08:02,603] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 11:08:02,608] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 11:08:02,609] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'CHEN/ZHIXUAN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'BRTQQ3', 'price': 15760, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'PVG', 'depDate': '201903312210', 'arrDate': '201904010005', 'carrier': 'MM', 'flightNumber': 'MM079'}], 'retSegments': None, 'passengers': [{'name': 'CHEN/ZHIXUAN', 'gender': 'M', 'birthday': '19990208', 'nationality': 'CN'}], 'baggages': [], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[32m[2019-01-28 11:15:33,436] [log.py:91] [log:__console] [INFO]- 获取到任务|[{'taskStatus': None, 'id': 1494196, 'taskType': 1, 'taskSource': 1, 'taskId': 65320, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_f08269284d37482aa9efe75be6a76cb7', 'orderNo': '391213009', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-03-18', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'SHIN/MYEONGSEOP', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'E7ANDB', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548645329000, 'createTime': 1548645329000}][0m
[31m[2019-01-28 11:15:33,438] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 11:18:06,675] [log.py:91] [log:__console] [INFO]- 获取到任务|[{'taskStatus': None, 'id': 1494200, 'taskType': 1, 'taskSource': 0, 'taskId': 963635, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 11, 'carrier': 'MM', 'orderCode': 'QUT_f5d2f2c6514d44cfac74c2bf9ab75522', 'orderNo': '1612569443588', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 2, 'name': 'LI/JIA', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': '', 'loginPassword': '', 'pnr': 'TY2UPA', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548645482000, 'createTime': 1548645482000}][0m
[31m[2019-01-28 11:18:06,678] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 11:29:03,493] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494200, 'taskType': 1, 'taskSource': 0, 'taskId': 963635, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 11, 'carrier': 'MM', 'orderCode': 'QUT_f5d2f2c6514d44cfac74c2bf9ab75522', 'orderNo': '1612569443588', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 2, 'name': 'LI/JIA', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': '', 'loginPassword': '', 'pnr': 'TY2UPA', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548646140000, 'createTime': 1548645482000}[0m
[32m[2019-01-28 11:29:18,828] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 11:29:18,829] [log.py:91] [log:__console] [INFO]- 获取到总价格：19860[0m
[32m[2019-01-28 11:29:18,830] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 11:29:18,857] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 11:29:18,860] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 11:29:18,861] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 11:29:18,863] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 11:29:18,864] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494200, 'taskType': 1, 'taskSource': 0, 'taskId': 963635, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 11, 'carrier': 'MM', 'orderCode': 'QUT_f5d2f2c6514d44cfac74c2bf9ab75522', 'orderNo': '1612569443588', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 2, 'name': 'LI/JIA', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': '', 'loginPassword': '', 'pnr': 'TY2UPA', 'price': 19860, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201904060850', 'arrDate': '201904061145', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LI/JIA', 'gender': 'F', 'birthday': '19951216', 'nationality': 'CN'}], 'baggages': [], 'updateTime': 1548646140000, 'createTime': 1548645482000}[0m
[32m[2019-01-28 11:29:19,309] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
[32m[2019-01-28 11:36:57,033] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494229, 'taskType': 1, 'taskSource': 1, 'taskId': 65340, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a22f0fe23426429fa15b57314f19c920', 'orderNo': '391222706', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-16', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548646615000, 'createTime': 1548646615000}[0m
[32m[2019-01-28 11:37:08,220] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 11:37:08,221] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 11:37:08,221] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 11:37:08,257] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 11:37:08,264] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 11:37:08,265] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 11:37:08,267] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 11:37:08,267] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494229, 'taskType': 1, 'taskSource': 1, 'taskId': 65340, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a22f0fe23426429fa15b57314f19c920', 'orderNo': '391222706', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-16', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 46460, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'name': 'LEI/HUI', 'baggageWeight': 20, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548646615000, 'createTime': 1548646615000}[0m
[32m[2019-01-28 11:37:09,885] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
[31m[2019-01-28 11:58:01,725] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[36m[2019-01-28 12:11:11,894] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:11:34,521] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:11:34,522] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:11:34,523] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:11:34,548] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:11:34,552] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:11:34,553] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:11:34,556] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:11:34,556] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 46460, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'name': 'LEI/HUI', 'baggageWeight': 20, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:12:31,393] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:12:43,102] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:12:43,104] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:12:43,105] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:12:47,551] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:12:47,568] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:12:47,569] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[36m[2019-01-28 12:15:20,286] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[31m[2019-01-28 12:15:52,592] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 12:15:52,593] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 12:15:52,596] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[36m[2019-01-28 12:16:01,189] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[31m[2019-01-28 12:16:28,301] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 12:16:28,303] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 12:16:28,304] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[36m[2019-01-28 12:16:34,740] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:17:07,422] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:17:07,424] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:17:07,425] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:17:07,451] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:17:07,457] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:17:07,458] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:17:19,305] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:17:19,312] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 43260, 'baggagePrice': 3200, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'name': 'LEI/HUI', 'baggageWeight': 20, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:21:52,071] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:22:03,470] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:22:03,472] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:22:03,473] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:22:03,498] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:22:03,504] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:22:03,504] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[36m[2019-01-28 12:31:12,270] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:31:26,011] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:31:26,013] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:31:26,014] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:31:26,042] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:31:26,049] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:31:26,050] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[31m[2019-01-28 12:31:31,879] [log.py:97] [log:__console] [ERROR]- 获取乘客信息失败，错误信息是：expected string or bytes-like object[0m
[32m[2019-01-28 12:31:31,882] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'N', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '获取信息失败', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 46460, 'baggagePrice': 0.0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': None, 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:31:59,284] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:32:12,083] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:32:12,086] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:32:12,088] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:32:12,118] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:32:12,124] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:32:12,125] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[36m[2019-01-28 12:32:54,508] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:33:09,436] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:33:09,438] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:33:09,438] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:33:09,466] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:33:09,472] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:33:09,473] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[31m[2019-01-28 12:33:14,691] [log.py:97] [log:__console] [ERROR]- 获取乘客信息失败，错误信息是：list index out of range[0m
[32m[2019-01-28 12:33:14,694] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'N', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '获取信息失败', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 46460, 'baggagePrice': 0.0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': None, 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:33:42,252] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:33:53,154] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:33:53,156] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:33:53,157] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:33:53,183] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:33:53,189] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:33:53,189] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:33:57,489] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:33:57,493] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 33660, 'baggagePrice': 12800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'baggageWeight': 80, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:36:54,060] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:37:05,261] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:37:05,263] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:37:05,264] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:37:05,292] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:37:05,299] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:37:05,299] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[36m[2019-01-28 12:39:05,528] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:39:18,959] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:39:18,961] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:39:18,962] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:39:18,994] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:39:19,001] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:39:19,001] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:39:35,516] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:39:35,518] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 33660, 'baggagePrice': 12800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'name': 'LEI/HUI', 'baggageWeight': 80, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:44:06,342] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:44:20,013] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:44:20,015] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:44:20,016] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:44:20,043] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:44:20,049] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:44:20,049] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:44:25,460] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:44:25,466] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 33660, 'baggagePrice': 12800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'name': 'LEI/HUI', 'baggageWeight': 80, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:52:17,161] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:52:28,656] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:52:28,716] [log.py:91] [log:__console] [INFO]- 获取到总价格：46460[0m
[32m[2019-01-28 12:52:28,717] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:52:28,760] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:52:28,779] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:52:28,781] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:52:32,197] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:52:32,205] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEI/HUI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'J9KR8P', 'price': 33660, 'baggagePrice': 12800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LEI/HUI', 'gender': 'F', 'birthday': '19900927', 'nationality': 'CN'}], 'baggages': [{'name': 'LEI/HUI', 'baggageWeight': 80, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[36m[2019-01-28 12:54:52,203] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 12:55:04,244] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 12:55:04,245] [log.py:91] [log:__console] [INFO]- 获取到总价格：37380[0m
[32m[2019-01-28 12:55:04,245] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 12:55:04,275] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 12:55:04,280] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 12:55:04,281] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 12:55:04,284] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 12:55:04,284] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'HND', 'arrCity': 'PVG', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LIN/XIUQIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '4ND3QD', 'price': 30580, 'baggagePrice': 6800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'HND', 'arr': 'PVG', 'depDate': '201904100245', 'arrDate': '201904100500', 'carrier': 'MM', 'flightNumber': 'MM899'}], 'retSegments': None, 'passengers': [{'name': 'LIN/XIUQIN', 'gender': 'F', 'birthday': '19630416', 'nationality': 'CN'}, {'name': 'GU/GUOXIANG', 'gender': 'M', 'birthday': '19630602', 'nationality': 'CN'}], 'baggages': [{'name': 'LIN/XIUQIN', 'baggageWeight': 20, 'dep': 'HND', 'arr': 'PVG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[32m[2019-01-28 13:18:58,088] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494366, 'taskType': 1, 'taskSource': 1, 'taskId': 65460, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_230b8fd1f6594634b6638d3947ebebce', 'orderNo': '391266086', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-06', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEE/YOUJUNG', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'JPUTGB', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548652734000, 'createTime': 1548652734000}[0m
[32m[2019-01-28 13:19:09,416] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 13:19:09,418] [log.py:91] [log:__console] [INFO]- 获取到总价格：42920[0m
[32m[2019-01-28 13:19:09,419] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 13:19:09,452] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 13:19:09,458] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 13:19:09,458] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 13:19:09,461] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 13:19:09,462] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494366, 'taskType': 1, 'taskSource': 1, 'taskId': 65460, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_230b8fd1f6594634b6638d3947ebebce', 'orderNo': '391266086', 'depCity': 'KIX', 'arrCity': 'PUS', 'fromDate': '2019-02-06', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LEE/YOUJUNG', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'JPUTGB', 'price': 42920, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'PUS', 'depDate': '201902061350', 'arrDate': '201902061525', 'carrier': 'MM', 'flightNumber': 'MM017'}], 'retSegments': None, 'passengers': [{'name': 'LEE/YOUJUNG', 'gender': 'F', 'birthday': '19730525', 'nationality': 'KR'}, {'name': 'KIM/YECHAN', 'gender': 'M', 'birthday': '20030714', 'nationality': 'KR'}], 'baggages': [], 'updateTime': 1548652734000, 'createTime': 1548652734000}[0m
[32m[2019-01-28 13:19:11,443] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
[32m[2019-01-28 14:48:56,315] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494499, 'taskType': 1, 'taskSource': 1, 'taskId': 65610, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 6, 'carrier': 'MM', 'orderCode': 'QUA_84ae468c1a80445a98c019013dbcb3f9', 'orderNo': '1631414634676', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-16', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LIN/CUIXIA', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'C23J9Y', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548658131000, 'createTime': 1548658131000}[0m
[32m[2019-01-28 14:49:07,826] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 14:49:07,827] [log.py:91] [log:__console] [INFO]- 获取到总价格：36860[0m
[32m[2019-01-28 14:49:07,827] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 14:49:07,854] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 14:49:07,858] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 14:49:07,858] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 14:49:07,861] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 14:49:07,861] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494499, 'taskType': 1, 'taskSource': 1, 'taskId': 65610, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 6, 'carrier': 'MM', 'orderCode': 'QUA_84ae468c1a80445a98c019013dbcb3f9', 'orderNo': '1631414634676', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-16', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LIN/CUIXIA', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'C23J9Y', 'price': 36320, 'baggagePrice': 540, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'HKG', 'depDate': '201902160820', 'arrDate': '201902161150', 'carrier': 'MM', 'flightNumber': 'MM063'}], 'retSegments': None, 'passengers': [{'name': 'LIN/CUIXIA', 'gender': 'F', 'birthday': '19940522', 'nationality': 'CN'}], 'baggages': [{'name': 'LIN/CUIXIA', 'baggageWeight': 20, 'dep': 'KIX', 'arr': 'HKG'}], 'updateTime': 1548658131000, 'createTime': 1548658131000}[0m
[32m[2019-01-28 14:49:08,803] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
[32m[2019-01-28 14:58:02,108] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494520, 'taskType': 1, 'taskSource': 1, 'taskId': 65620, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a48cba6ca5324d508becc9f40d2bf19c', 'orderNo': '391306196', 'depCity': 'CTS', 'arrCity': 'TPE', 'fromDate': '2019-03-15', 'retDate': None, 'flightNumber': 'MM725', 'tripType': 1, 'name': 'WANG/CHINHSIEN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'G99D5Y', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548658681000, 'createTime': 1548658681000}[0m
[32m[2019-01-28 14:58:14,989] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 14:58:14,991] [log.py:91] [log:__console] [INFO]- 获取到总价格：16150[0m
[32m[2019-01-28 14:58:14,992] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 14:58:15,016] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 14:58:15,019] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 14:58:15,020] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 14:58:15,022] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 14:58:15,022] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494520, 'taskType': 1, 'taskSource': 1, 'taskId': 65620, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_a48cba6ca5324d508becc9f40d2bf19c', 'orderNo': '391306196', 'depCity': 'CTS', 'arrCity': 'TPE', 'fromDate': '2019-03-15', 'retDate': None, 'flightNumber': 'MM725', 'tripType': 1, 'name': 'WANG/CHINHSIEN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'G99D5Y', 'price': 16150, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'CTS', 'arr': 'TPE', 'depDate': '201903151630', 'arrDate': '201903152020', 'carrier': 'MM', 'flightNumber': 'MM725'}], 'retSegments': None, 'passengers': [{'name': 'WANG/CHINHSIEN', 'gender': 'M', 'birthday': '19900706', 'nationality': 'TW'}], 'baggages': [], 'updateTime': 1548658681000, 'createTime': 1548658681000}[0m
[32m[2019-01-28 14:58:16,551] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
[32m[2019-01-28 15:32:57,031] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494568, 'taskType': 1, 'taskSource': 1, 'taskId': 65673, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_d1a5c00ca27c4aaa937ff4242d22cb70', 'orderNo': '391319408', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-08', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'HASHIMOTO/KAZUHIKO', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'TVHCQ7', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548660774000, 'createTime': 1548660774000}[0m
[31m[2019-01-28 15:33:17,345] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 15:33:17,347] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:33:17,348] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:33:17,349] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 15:37:59,124] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494573, 'taskType': 1, 'taskSource': 1, 'taskId': 65677, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_c2055d689b95438b950c7c3690137a6b', 'orderNo': '391321447', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'TAN/RUIJUN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'Y89BTS', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548661078000, 'createTime': 1548661078000}[0m
[31m[2019-01-28 15:38:20,373] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 15:38:20,375] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:38:20,376] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:38:20,377] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 15:43:04,099] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494568, 'taskType': 1, 'taskSource': 1, 'taskId': 65673, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_d1a5c00ca27c4aaa937ff4242d22cb70', 'orderNo': '391319408', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-08', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'HASHIMOTO/KAZUHIKO', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'TVHCQ7', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548661380000, 'createTime': 1548660774000}[0m
[31m[2019-01-28 15:43:24,352] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 15:43:24,356] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:43:24,356] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:43:24,357] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 15:48:00,833] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494573, 'taskType': 1, 'taskSource': 1, 'taskId': 65677, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_c2055d689b95438b950c7c3690137a6b', 'orderNo': '391321447', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'TAN/RUIJUN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'Y89BTS', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548661680000, 'createTime': 1548661078000}[0m
[31m[2019-01-28 15:48:21,113] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 15:48:21,114] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:48:21,116] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:48:21,116] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 15:54:03,148] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494568, 'taskType': 1, 'taskSource': 1, 'taskId': 65673, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_d1a5c00ca27c4aaa937ff4242d22cb70', 'orderNo': '391319408', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-08', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'HASHIMOTO/KAZUHIKO', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'TVHCQ7', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548662040000, 'createTime': 1548660774000}[0m
[31m[2019-01-28 15:54:23,412] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 15:54:23,416] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:54:23,417] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 15:54:23,418] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 16:00:23,522] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494573, 'taskType': 1, 'taskSource': 1, 'taskId': 65677, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_c2055d689b95438b950c7c3690137a6b', 'orderNo': '391321447', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'TAN/RUIJUN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'Y89BTS', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548662422000, 'createTime': 1548661078000}[0m
[31m[2019-01-28 16:00:44,266] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> HTTPSConnectionPool(host='ezy.flypeach.com', port=443): Read timed out. (read timeout=20)[0m
[31m[2019-01-28 16:00:44,269] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:00:44,269] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:00:44,270] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 16:05:27,574] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494607, 'taskType': 1, 'taskSource': 1, 'taskId': 65709, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 3, 'carrier': 'MM', 'orderCode': 'QTH_dd01bff4c1f5469bbdcde78ed58261c1', 'orderNo': 'xnm190128160142860e955f', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-04', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LIN/XIAOYIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '5CAQG6', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548662726000, 'createTime': 1548662642000}[0m
[31m[2019-01-28 16:06:21,922] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> ('Connection aborted.', OSError("(60, 'ETIMEDOUT')",))[0m
[31m[2019-01-28 16:06:21,924] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:06:21,925] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:06:21,926] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 16:06:22,372] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494568, 'taskType': 1, 'taskSource': 1, 'taskId': 65673, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_d1a5c00ca27c4aaa937ff4242d22cb70', 'orderNo': '391319408', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-08', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'HASHIMOTO/KAZUHIKO', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'TVHCQ7', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548662780000, 'createTime': 1548660774000}[0m
[32m[2019-01-28 16:11:02,402] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494573, 'taskType': 1, 'taskSource': 1, 'taskId': 65677, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_c2055d689b95438b950c7c3690137a6b', 'orderNo': '391321447', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'TAN/RUIJUN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'Y89BTS', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548663060000, 'createTime': 1548661078000}[0m
[31m[2019-01-28 16:13:52,419] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> ('Connection aborted.', OSError("(60, 'ETIMEDOUT')",))[0m
[31m[2019-01-28 16:13:52,420] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:13:52,422] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:13:52,425] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 16:16:01,218] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494607, 'taskType': 1, 'taskSource': 1, 'taskId': 65709, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 3, 'carrier': 'MM', 'orderCode': 'QTH_dd01bff4c1f5469bbdcde78ed58261c1', 'orderNo': 'xnm190128160142860e955f', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-04', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LIN/XIAOYIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '5CAQG6', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548663360000, 'createTime': 1548662642000}[0m
[32m[2019-01-28 16:20:09,556] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494568, 'taskType': 1, 'taskSource': 1, 'taskId': 65673, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_d1a5c00ca27c4aaa937ff4242d22cb70', 'orderNo': '391319408', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-08', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'HASHIMOTO/KAZUHIKO', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'TVHCQ7', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548663604000, 'createTime': 1548660774000}[0m
[31m[2019-01-28 16:21:23,274] [log.py:97] [log:__console] [ERROR]- 获取航班信息出错，错误信息为：-> ('Connection aborted.', OSError("(60, 'ETIMEDOUT')",))[0m
[31m[2019-01-28 16:21:23,277] [log.py:97] [log:__console] [ERROR]- 获取总价格失败，错误信息为'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:21:23,278] [log.py:97] [log:__console] [ERROR]- 获取币种失败，错误信息是：'AirMM' object has no attribute 'content'[0m
[31m[2019-01-28 16:21:23,279] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 16:22:05,629] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494573, 'taskType': 1, 'taskSource': 1, 'taskId': 65677, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_c2055d689b95438b950c7c3690137a6b', 'orderNo': '391321447', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-06', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'TAN/RUIJUN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'Y89BTS', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548663720000, 'createTime': 1548661078000}[0m
[31m[2019-01-28 16:25:30,925] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,927] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,930] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,932] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,934] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,936] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,938] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,940] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,943] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,946] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,948] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,950] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,952] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,954] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,956] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,958] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,960] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,962] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,964] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,966] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,969] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,970] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,972] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,975] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,977] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,979] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,981] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,983] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,985] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,987] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,989] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,992] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,994] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,995] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,997] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:30,999] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,002] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,004] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,005] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,008] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,010] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,012] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,014] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,016] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,018] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,020] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,022] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,024] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,026] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,028] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,030] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,032] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,034] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,036] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,038] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,040] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,043] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,045] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,047] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,049] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,051] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,053] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,055] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,057] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,060] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,061] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,064] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,065] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,067] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,070] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,072] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,073] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,075] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,077] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,080] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,082] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,084] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,086] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,087] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,089] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,092] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,094] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,096] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,098] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,100] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,102] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,104] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,106] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,108] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,110] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,113] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,115] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,117] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,118] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,120] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,122] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,124] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,127] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,128] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,131] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,132] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,134] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,142] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,150] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,153] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,156] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,159] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,162] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,164] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,166] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,168] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,170] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,172] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,174] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,177] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,179] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,182] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,184] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,187] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,189] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,191] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,195] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,197] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,199] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,200] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,203] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,206] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,209] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,211] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,214] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,216] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,219] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,221] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,223] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,226] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,228] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,230] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,233] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,235] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,237] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,239] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,244] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,246] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,248] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,250] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,253] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,256] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,258] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,260] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,262] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,264] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,268] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,273] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,278] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,280] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,282] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,285] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,287] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,289] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,291] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,294] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,296] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,298] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,300] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,302] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,304] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,306] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,308] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,311] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,313] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,315] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,317] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,319] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,321] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,323] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,326] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,328] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,330] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,332] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,333] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,335] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,338] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,340] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,343] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,346] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,349] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,351] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,353] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,355] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,357] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,360] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,362] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,364] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,366] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,369] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,371] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,373] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,375] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,379] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,382] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,384] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,386] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,388] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,390] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,394] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,396] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,398] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,400] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,403] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,405] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,408] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,410] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,413] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,415] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,417] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,420] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,422] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,424] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,427] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,430] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,432] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,434] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,436] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,440] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,443] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,445] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,447] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,448] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,450] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,452] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,454] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,456] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,458] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,460] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,462] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,464] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,466] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,468] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,470] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,471] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,473] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,475] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,477] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,479] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,481] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,483] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,485] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,487] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,489] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,491] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,493] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,494] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,496] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,499] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,501] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,502] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,504] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,506] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,508] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,510] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,512] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,514] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,516] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,518] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,519] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,522] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,524] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,526] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,528] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,530] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,531] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,533] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,535] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,537] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,539] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,541] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,543] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,545] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,548] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,553] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,557] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,559] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,561] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,564] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,567] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,569] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,571] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,573] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,576] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,578] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,581] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,583] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,585] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,587] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,590] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,594] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,596] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,598] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,600] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,603] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,606] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,608] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,610] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,613] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,616] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,618] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,620] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,622] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,625] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,628] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,630] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,632] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,634] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,638] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,640] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,642] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,644] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,646] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,649] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,651] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,653] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,655] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,657] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,660] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,662] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,664] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,666] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,668] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,670] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,672] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,674] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,676] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,678] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,680] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,681] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,683] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,685] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,687] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,689] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,691] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,693] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,695] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,697] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,699] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,701] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,703] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,705] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,707] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,709] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,711] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,713] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,715] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,717] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,719] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,721] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,723] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,724] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,726] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,728] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,730] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,732] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,734] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,736] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,738] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,740] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,742] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,744] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,746] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,749] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,753] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,756] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,758] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,761] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,771] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,774] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,778] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,780] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,783] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,786] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,788] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,791] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,794] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,796] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,798] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,801] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,803] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,805] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,807] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,810] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,813] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,816] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,818] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,820] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,823] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,825] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,829] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,831] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,832] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,835] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,837] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,840] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,843] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,845] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,848] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,851] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,853] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,855] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,857] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,860] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,862] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,864] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,866] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,868] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,870] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,873] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,875] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,877] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,879] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,881] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,883] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,885] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,887] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,889] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,891] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,893] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,895] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,898] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,900] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,902] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,904] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,906] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,908] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,910] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,912] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,914] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,916] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,918] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,921] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,922] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,925] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,926] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,929] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,931] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,933] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,935] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,937] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,939] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,941] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,943] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,946] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,947] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,949] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,952] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,954] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,958] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,960] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,964] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,966] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,969] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,972] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,974] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,977] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,980] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,982] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,985] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,987] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,988] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,992] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,994] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,997] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:31,999] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,002] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,005] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,008] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,011] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,013] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,016] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,019] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,021] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,023] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,026] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,029] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,032] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,034] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,036] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,038] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,041] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,045] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,047] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,049] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,052] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,055] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,058] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,061] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,063] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,065] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,067] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,069] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,072] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,074] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,076] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,078] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,080] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,082] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,084] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,086] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,089] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,091] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,093] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,095] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,097] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,099] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,102] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,104] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,106] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,109] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,111] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,113] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,115] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,117] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,119] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,121] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,123] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,125] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,128] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,130] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,131] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,133] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,136] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,138] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,140] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,142] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,144] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,146] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,148] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,150] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,152] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,154] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,156] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,159] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,163] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,165] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,167] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,170] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,172] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,175] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,178] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,180] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,182] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,185] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,188] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,190] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,192] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,197] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,200] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,202] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,203] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,205] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,208] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,211] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,214] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,216] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,218] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,221] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,227] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,231] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,235] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,237] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,239] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,242] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,245] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,248] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,250] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,253] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,255] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,258] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,261] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,263] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,265] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,267] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,269] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,270] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,273] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,275] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,278] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,280] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,282] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,284] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,286] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,288] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,290] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,292] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,295] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,297] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,299] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,301] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,303] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,305] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,307] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,309] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,311] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,313] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,315] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,317] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,319] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,321] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,323] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,325] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,327] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,329] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,331] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,333] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,336] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,337] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,340] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,342] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,344] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,346] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,348] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,350] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,352] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,354] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,356] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,358] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,361] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,365] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,368] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,370] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,372] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,374] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,377] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,379] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,383] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,385] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,387] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,389] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,394] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,396] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,398] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,400] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,404] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,406] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,408] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,411] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,413] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,416] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,419] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,421] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,423] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,425] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,430] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,432] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,434] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,436] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,439] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,442] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,445] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,447] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,450] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,453] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,455] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,457] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,460] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,462] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,466] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,468] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,470] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,472] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,474] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,478] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,480] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,482] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,484] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,485] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,488] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,490] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,492] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,494] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,496] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,498] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,500] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,502] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,504] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,506] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,508] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,510] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,512] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,514] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,573] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,584] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,592] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,599] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,606] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,612] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,617] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,625] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,635] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,641] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,649] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,654] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,660] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,663] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,668] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,672] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,675] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,679] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,682] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,685] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,688] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,691] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,694] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,697] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,700] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,703] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,709] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,714] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,720] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,723] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,728] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,730] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,733] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,736] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,740] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,743] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,745] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,748] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,751] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,754] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,757] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,760] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,763] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,766] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,769] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,772] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,777] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,781] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,785] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,789] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,792] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,796] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,800] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,803] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,805] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,809] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,814] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,817] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,821] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,826] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,829] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,833] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,837] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,840] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,845] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,849] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,852] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,856] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,861] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,864] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,868] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,872] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,876] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,879] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,884] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,887] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,890] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,894] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,897] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,900] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,903] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,906] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,909] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,913] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,916] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,918] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,921] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,925] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,927] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,930] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,934] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,937] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,940] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,943] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,946] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,949] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,952] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,955] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,957] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,960] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,963] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,966] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,971] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,974] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,978] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,981] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,985] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,989] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,994] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:32,997] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,000] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,004] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,006] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,010] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,013] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,017] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,019] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,023] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,029] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,033] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,037] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,041] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,048] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,052] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,055] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,060] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,065] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,067] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,071] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,075] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,079] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,082] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,087] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,090] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,094] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,097] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,100] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,112] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,123] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,128] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,132] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,137] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,142] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,146] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,150] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,154] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,161] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,166] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,170] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,174] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,178] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,182] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,185] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,192] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,199] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,202] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,206] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,213] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,227] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,232] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,236] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,241] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,249] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,254] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,257] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,264] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,271] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,282] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,286] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,292] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,296] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,304] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,308] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,312] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,315] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,318] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,321] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,325] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,328] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,333] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,336] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,342] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,346] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,350] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,354] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,358] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,361] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,364] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,368] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,371] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,374] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,377] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,380] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,383] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,387] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,390] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[31m[2019-01-28 16:25:33,395] [log.py:97] [log:__console] [ERROR]- 获取任务失败[0m
[32m[2019-01-28 16:27:02,231] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494607, 'taskType': 1, 'taskSource': 1, 'taskId': 65709, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 3, 'carrier': 'MM', 'orderCode': 'QTH_dd01bff4c1f5469bbdcde78ed58261c1', 'orderNo': 'xnm190128160142860e955f', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-04-04', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'LIN/XIAOYIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '5CAQG6', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548664020000, 'createTime': 1548662642000}[0m
[32m[2019-01-28 16:31:04,932] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494568, 'taskType': 1, 'taskSource': 1, 'taskId': 65673, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_d1a5c00ca27c4aaa937ff4242d22cb70', 'orderNo': '391319408', 'depCity': 'KIX', 'arrCity': 'HKG', 'fromDate': '2019-02-08', 'retDate': None, 'flightNumber': 'MM063', 'tripType': 1, 'name': 'HASHIMOTO/KAZUHIKO', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'TVHCQ7', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548664260000, 'createTime': 1548660774000}[0m
[36m[2019-01-28 16:36:42,322] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[36m[2019-01-28 16:59:17,967] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[36m[2019-01-28 17:04:52,634] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[36m[2019-01-28 17:05:15,210] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[36m[2019-01-28 17:33:46,273] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[36m[2019-01-28 17:39:56,296] [log.py:93] [log:__console] [DEBUG]- 测试数据[0m
[32m[2019-01-28 17:40:09,039] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 17:40:09,041] [log.py:91] [log:__console] [INFO]- 获取到总价格：37380[0m
[32m[2019-01-28 17:40:09,041] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 17:40:09,080] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 17:40:09,086] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 17:40:09,086] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 17:40:09,091] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 17:40:09,091] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1475140, 'taskType': 1, 'taskSource': 1, 'taskId': 61286, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_ebf14bd694024ea881fc75fdcdaa66ff', 'orderNo': '389936026', 'depCity': 'HND', 'arrCity': 'PVG', 'fromDate': '2019-02-21', 'retDate': None, 'flightNumber': 'MM017', 'tripType': 1, 'name': 'LIN/XIUQIN', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '4ND3QD', 'price': 30580, 'baggagePrice': 6800, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'HND', 'arr': 'PVG', 'depDate': '201904100245', 'arrDate': '201904100500', 'carrier': 'MM', 'flightNumber': 'MM899'}], 'retSegments': None, 'passengers': [{'name': 'GU/GUOXIANG', 'gender': 'M', 'birthday': '19630602', 'nationality': 'CN'}, {'name': 'LIN/XIUQIN', 'gender': 'F', 'birthday': '19630416', 'nationality': 'CN'}], 'baggages': [{'name': 'LIN/XIUQIN', 'baggageWeight': 20, 'dep': 'HND', 'arr': 'PVG'}], 'updateTime': 1548330704000, 'createTime': 1548330704000}[0m
[32m[2019-01-28 17:41:38,304] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494734, 'taskType': 1, 'taskSource': 1, 'taskId': 65812, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_abedbfeb09fa476fa276a336fdb1cf87', 'orderNo': '391367222', 'depCity': 'KIX', 'arrCity': 'ICN', 'fromDate': '2019-04-19', 'retDate': None, 'flightNumber': 'MM011', 'tripType': 1, 'name': 'SHIN/MOONTAE', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'UFZ7G9', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548668496000, 'createTime': 1548668150000}[0m
[32m[2019-01-28 17:41:50,752] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 17:41:50,754] [log.py:91] [log:__console] [INFO]- 获取到总价格：8360[0m
[32m[2019-01-28 17:41:50,756] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 17:41:50,785] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 17:41:50,789] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 17:41:50,789] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 17:41:50,793] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 17:41:50,793] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494734, 'taskType': 1, 'taskSource': 1, 'taskId': 65812, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_abedbfeb09fa476fa276a336fdb1cf87', 'orderNo': '391367222', 'depCity': 'KIX', 'arrCity': 'ICN', 'fromDate': '2019-04-19', 'retDate': None, 'flightNumber': 'MM011', 'tripType': 1, 'name': 'SHIN/MOONTAE', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': 'UFZ7G9', 'price': 8360, 'baggagePrice': 0, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'ICN', 'depDate': '201904192000', 'arrDate': '201904192150', 'carrier': 'MM', 'flightNumber': 'MM011'}], 'retSegments': None, 'passengers': [{'name': 'SHIN/MOONTAE', 'gender': 'M', 'birthday': '19561117', 'nationality': 'KR'}], 'baggages': [], 'updateTime': 1548668496000, 'createTime': 1548668150000}[0m
[32m[2019-01-28 17:41:52,525] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
[32m[2019-01-28 18:08:59,184] [log.py:91] [log:__console] [INFO]- 获取到任务|{'taskStatus': None, 'id': 1494776, 'taskType': 1, 'taskSource': 1, 'taskId': 65856, 'status': 1, 'pathStatus': 0, 'pnrStatus': '', 'msg': '', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_05b516b8fdf442c2901fce024895b587', 'orderNo': '391379116', 'depCity': 'KIX', 'arrCity': 'CTS', 'fromDate': '2019-04-25', 'retDate': None, 'flightNumber': 'MM105', 'tripType': 1, 'name': 'NAKAJIMA/YOSHI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '5XAFWH', 'price': 0.0, 'baggagePrice': 0.0, 'cur': '', 'path': None, 'fromSegments': None, 'retSegments': None, 'passengers': None, 'baggages': None, 'updateTime': 1548670136000, 'createTime': 1548670136000}[0m
[32m[2019-01-28 18:09:15,063] [log.py:91] [log:__console] [INFO]- 获取任务对应信息[0m
[32m[2019-01-28 18:09:15,067] [log.py:91] [log:__console] [INFO]- 获取到总价格：15420[0m
[32m[2019-01-28 18:09:15,068] [log.py:91] [log:__console] [INFO]- 获取到支付货币的币种[0m
[32m[2019-01-28 18:09:15,100] [log.py:91] [log:__console] [INFO]- 记录航班起飞落地时间[0m
[32m[2019-01-28 18:09:15,105] [log.py:91] [log:__console] [INFO]- 获取乘客基本信息[0m
[32m[2019-01-28 18:09:15,105] [log.py:91] [log:__console] [INFO]- 修改pnr状态为confirm[0m
[32m[2019-01-28 18:09:15,108] [log.py:91] [log:__console] [INFO]- 获取乘客的行李信息[0m
[32m[2019-01-28 18:09:15,108] [log.py:91] [log:__console] [INFO]- 回填数据：{'taskStatus': 'Y', 'id': 1494776, 'taskType': 1, 'taskSource': 1, 'taskId': 65856, 'status': 1, 'pathStatus': 0, 'pnrStatus': 'confirm', 'msg': '成功', 'source': 2, 'carrier': 'MM', 'orderCode': 'CTR_05b516b8fdf442c2901fce024895b587', 'orderNo': '391379116', 'depCity': 'KIX', 'arrCity': 'CTS', 'fromDate': '2019-04-25', 'retDate': None, 'flightNumber': 'MM105', 'tripType': 1, 'name': 'NAKAJIMA/YOSHI', 'email': 'letaohangkong@163.com', 'accountType': '0', 'loginAccount': None, 'loginPassword': None, 'pnr': '5XAFWH', 'price': 14880, 'baggagePrice': 540, 'cur': 'JPY', 'path': None, 'fromSegments': [{'segmentindex': 1, 'dep': 'KIX', 'arr': 'CTS', 'depDate': '201904251035', 'arrDate': '201904251235', 'carrier': 'MM', 'flightNumber': 'MM105'}], 'retSegments': None, 'passengers': [{'name': 'NAKAJIMA/RYUKI', 'gender': 'M', 'birthday': '19920112', 'nationality': 'JP'}, {'name': 'NAKAJIMA/YOSHI', 'gender': 'F', 'birthday': '19910710', 'nationality': 'JP'}], 'baggages': [{'name': 'NAKAJIMA/YOSHI', 'baggageWeight': 20, 'dep': 'KIX', 'arr': 'CTS'}], 'updateTime': 1548670136000, 'createTime': 1548670136000}[0m
[32m[2019-01-28 18:09:17,219] [log.py:91] [log:__console] [INFO]- 回填状态 -> {"msg":"success","status":"Y","data":null,"success":true}[0m
